#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,            ,             tmotorVex269_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,            ,             tmotorVex269_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,            ,             tmotorVex269_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//enable and disable strafeing in code
#define strafeEnable

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	float leftStk = 0;
	float rightStk = 0;
	float transStk = 0;
	bool precisionToggle = false;

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    //UserControlCodePlaceholderForTesting();

    //update stick inputs
    if(precisionToggle)
    {
    	leftStk = vexRT[Ch1] / 4;
    	rightStk = vexRT[Ch3] / 4;
    	transStk = vexRT[Ch4] / 4;
    }
    else
    {
    	leftStk = vexRT[Ch1] * .80;
   	  rightStk = vexRT[Ch3] * .80;
   	  transStk = vexRT[Ch4] * .80;
   	}

   	if(vexRT[Btn8R])
  	{
  		precisionToggle = true;
  	}
  	if(vexRT[Btn8D])
  	{
  		precisionToggle = false;
  	}

#ifndef strafeEnable
    motor[port2] = leftStk + rightStk;
    motor[port3] = leftStk + rightStk;
    motor[port6] = leftStk + rightStk;
    motor[port7] = leftStk + rightStk;

    motor[port4] = leftStk - rightStk;
    motor[port5] = leftStk - rightStk;
    motor[port8] = leftStk - rightStk;
    motor[port9] = leftStk - rightStk;
#endif

#ifdef strafeEnable
	  if(transStk > 5)
    {
    	motor[port2] = leftStk + rightStk + transStk;
    	motor[port3] = leftStk + rightStk + transStk;
    	motor[port6] = leftStk + rightStk + transStk;
    	motor[port7] = leftStk + rightStk + transStk;

    	motor[port4] = leftStk - rightStk - 127 * 0.15;
    	motor[port5] = leftStk - rightStk - 127 * 0.15;
    	motor[port8] = leftStk - rightStk - 127 * 0.15;
    	motor[port9] = leftStk - rightStk - 127 * 0.15;
    }
    else if(transStk < -5)
    {
    	motor[port2] = leftStk + rightStk + 127 * 0.15;
    	motor[port3] = leftStk + rightStk + 127 * 0.15;
    	motor[port6] = leftStk + rightStk + 127 * 0.15;
    	motor[port7] = leftStk + rightStk + 127 * 0.15;

    	motor[port4] = leftStk - rightStk + transStk;
    	motor[port5] = leftStk - rightStk + transStk;
    	motor[port8] = leftStk - rightStk + transStk;
    	motor[port9] = leftStk - rightStk + transStk;
    }
    else
    {
    	motor[port2] = leftStk + rightStk;
    	motor[port3] = leftStk + rightStk;
    	motor[port6] = leftStk + rightStk;
    	motor[port7] = leftStk + rightStk;

    	motor[port4] = leftStk - rightStk;
    	motor[port5] = leftStk - rightStk;
    	motor[port8] = leftStk - rightStk;
    	motor[port9] = leftStk - rightStk;
    }
#endif

  }
}
